### ISSUE TITLE
mandatory

### ISSUE THREAD

**Issue by VegarRingdalAibel** [vegarringdal/simple-html#55]
This only works if cell is empty..
not `mandatoryOnlyIfEmpty ` has no effect since its not added/used

https://github.com/vegarringdal/simple-html/blob/master/packages/grid/src/grid/gridFunctions/renderRowCell.ts#L66

**Comment by vegarringdal** [comment]
you can use the `cellAppendClassSetter` on grid interface to have own logic for coloring
