### ISSUE TITLE
add data- attributes for styling

### ISSUE THREAD

**Issue by VegarRingdalAibel** [vegarringdal/simple-html#56]
Add data- attributes for styling text/background

data-attribute-row-cell
data-attribute-row-cell-dimmed
data-attribute-header-label

Maybe add to group rows also?

Maybe we could also add a attribute to config on styles we want it to add?

cellAddClass
cellDimmedAddClass
labelAddClass

?

Even having a callback on this to set class based on row values might be useful

**Comment by vegarringdal** [comment]
added
