### ISSUE TITLE
When scrolled to the right and setting editor grid looses header

### ISSUE THREAD

**Issue by VegarRingdalAibel** [vegarringdal/simple-html#58]
Grid needs to rerender header

![image](https://github.com/user-attachments/assets/d9bed54d-bfcf-4939-910a-dbe01ac93f4a)

**Comment by vegarringdal** [comment]
Only happends if you force rebuild of header columns in "filter-operator-event"

trigger scroll to force update it
`gridInterface.triggerScrollEvent();`
